# Generated by Django 5.2.1 on 2025-05-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Bu email adresi zaten kayıtlı.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
