# Generated by Django 5.2.1 on 2025-05-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('B', 'Buyer'), ('S', 'Seller')], default='B', max_length=1),
        ),
    ]
